# -*- coding: utf-8 -*-
"""homework10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11tl7W1OrjvqDXx6IxqjpqVKlI2v9ufCh
"""

import pandas as pd
import plotly.express as px
import gradio as gr

df = pd.read_csv("blue_ridge_financials.csv")
def mystic_roast(territory):
  if territory != "All":
    brew = df[df["Region"] == territory]
  else:
    brew = df.copy()

    fig_latte = px.line (brew, x="Month", y=["Revenue","Cost"],
                        title = f"  Brewed Profits -{territory}",
                        template="plotly_white")
    fig_mocha = px.bar(brew, x="month,", y="Margin", color="Region",
                       title="Profit Margin (%) Over Time",
                       template= "plotly_white")

    return [fig_latte, fig_mocha]

demo = gr.Interface(
    fn=mystic_roast,
    inputs=[gr.Dropdown(["All"] + sorted(df["Region"].unique()),
                        value="All", label="Territory")],
    outputs=[gr.Plot(label="Revenue vs Cost"),
             gr.Plot(label="Profit Margin")],
    title="   Blue Ridge Dashboard of Destiny",
    description="Explore the regions of flavor and finance interactively."
)

demo.launch(share=True)