# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLS_ZNi5juAW0iQY-g-cmmo5eiCX7dPx
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df=pd.read_csv('Advertising_F.csv')
df.head()

#show admin stuff
st.title("Advertising Effectiveness Dashboard_Kai")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("X-Axis",['TV','radio','newspaper'])
y_var=st.sidebar.selectbox("Y-Axis",['sales'])
#Show a charter plot
fig=px.scatter(df,x=x_var,y=y_var,trendline='ols')
st.plotly_chart(fig)
#Show the data frame
st.write('### Data frame')
st.dataframe(df)

st.title("I'm the MAP!!!")
fig = px.scatter_mapbox(df,lat='latitude',lon= 'longitude',color='sales',
                        size='TV',hover_name='City')
fig.update_layout(mapbox_style="carto-positron")
st.plotly_chart(fig)

